const products = [
    {
        id:1,
        title: "Culpa Mia de Mercedes Ron",
        description: "Nicholas Leister ha sido creado para amargarme la vida. Alto, ojos azules, pelo negro como la noche... Suena genial ¿verdad? Pues no tanto cuando te enteras de que va a ser tu hermanastro y además representa todo de lo que has estado huyendo desde que tienes uso de razón.Peligro fue lo primero que me vino a la cabeza cuando lo conocí y descubrí que mantiene una doble vida oculta de su padre multimillonario.¿Cómo terminé cayendo en sus redes? Fácil: con esos ojos es capaz de poner tu mundo patas arriba",
        category:"Romantico",
        price: 880,
        image: 'CulpaMia.jfif',
        stock: 5,
    },
    {
        id:2,
        title: "Culpa Tuya de Mercedes Ron",
        description: "Más romance, traición y misterio en Culpa tuya, segunda parte de Culpa Mia, la saga romántica protagonizada por un chico malo con un gran corazón y una chica buena con muchas agallas.Cuando Noah se enamoró de Nick sabía que su relación no iba a ser fácil: son polos opuestos, fuego y electricidad, y cuando están juntos saltan chispas... en todos los sentidos.Hasta ahora, la pasión ha sido más fuerte que el orgullo, pero la diferencia de edad, la universidad, las fiestas, sus padres y los fantasmas que acechan a los dos les ponen a prueba una y otra vez, como una bomba de relojería que amenaza con hacerles estallar.¿Está Noah realmente preparada para enfrentarse a sus miedos y volver a confiar en alguien?¿Podrá Nicholas dejar atrás su pasado y abrir el corazón a una sola persona?",
        category:"Romantico",
        price: 880,
        image: 'CulpaTuya.jfif',
        stock: 5,
    },
    {
        id:3,
        title: "Culpa Nuestra de Mercedes Ron",
        description: "La relación de Nick y Noah está atravesando su peor momento, y parece que nada podrá volver a ser como antes... Van a tener que pasar por muchas cosas para finalmente comprender si de verdad están hechos el uno para el otro o si, por lo contrario, estar separados es lo que de verdad les conviene.Pero ¿acaso se puede olvidar un amor tan fuerte? ¿Cómo pueden borrarse los recuerdos tatuados en el corazón? El amor no siempre es suficiente y el perdón a veces no basta para solucionar las cosas. ¿Serán capaces de dejar atrás el pasado y volver a empezar?el pasado",
        category:"Romantico",
        price: 1000,
        image: 'CulpaNuestra.jfif',
        stock: 2,
    },
    {
        id:4,
        title: "Perfecto Mentiroso, Mentiras y secretos de Alex Mirez",
        description: "Una historia llena de mentiras y secretos, atracción y odio en la que nadie parece decir la verdad. ¿Hay algo más adictivo que desenmascarar a los Perfectos mentirosos? Las mejores historias de Wattpad ahora también en papel. Jude acaba de llegar a una de las universidades más elitistas del mundo, pero ya se ha dado cuenta que ahí todo se mueve alrededor de las fiestas, los cotilleos y los ligues entre estudiantes. Y que todo eso gira en torno a un trio irresistible: los hermanos Cash. Son vacilones, astutos, pero insoportablemente atractivos y poderosos. Y por encima de todo están acostumbrados a liderar el campus con sus juegos de niños ricos. Lo que no saben es que Jude tiene un plan: sacar a la luz sus más oscuros y perversos secretos, esos tan bien escondidos tras el lujoso apellido Cash.",
        category:"Romantico",
        price: 900,
        image: 'PerfectoMentiroso.jfif',
        stock: 10,
    },
    {
        id:5,
        title: "Perfecto Mentiroso, Peligros y verdades de Alex Mirez",
        description: "El desenlace de Perfectos mentirosos. Un final que nos dejará sin aliento, una historia con muchas mentiras, pasiones y odios.¿Hay algo más adictivo que los hermanos Cash?Jude llega a la prestigiosa Universidad de Tangus con un plan: sacar a la luz los más oscuros y perversos secretos de los hermanos Cash, esos tan bien escondidos tras su lujoso apellido, perfecta apariencia y carisma.Pero los Cash no son los únicos que guardan terribles secretos. Jude también se descubre como una perfecta mentirosa. Por fin se develarán todos los secretos y mentiras.",
        category:"Romantico",
        price: 1500,
        image: 'Perfectomentiroso2.jfif',
        stock: 10,
    },

    {
        id:6,
        title: "Anhelo de Tracy Wolff",
        description: "Mi mundo cambió en el instante en el que pisé el instituto Katmere. Aquí todo resulta extraño: la escuela, los alumnos, las asignaturas; y yo no soy más que una simple mortal entre ellos, dioses... o monstruos. Todavía no sé a qué bando pertenezco, si es que pertenezco a alguno, sólo sé que lo que parece unirlos a todos es su odio hacia mí.Pero entre ellos está Jaxon Vega, un vampiro que esconde oscuros secretos y que no ha sentido nada durante un siglo. Algo en él me atrae, apenas lo conozco, pero sé que hay algo roto en su interior que de alguna manera encaja con lo que hay roto en mí. Acercarme a él puede significar el fin del mundo, pero empiezo a sospechar que alguien me ha traído a este lugar a propósito, y tengo que descubrir por qué",
        category:"Fantasia",
        price: 1400,
        image: 'Anhelo.jpeg',
        stock: 1,
    },
    {
        id:7,
        title: "Furia de Tracy Wolff",
        description: "He vuelto al Instituto Katmere, pero me siento extraña, me atormentan cosas que no recuerdo haber vivido, y sigo luchando por comprender quién o qué soy realmente. Cuando empiezo a sentirme segura de nuevo, Hudson reaparece con sus ideas de venganza, insiste en que hay secretos que no conozco, secretos que pueden abrir una brecha entre Jaxon y yo para siempre. Pero enemigos mucho peores nos están esperando…Con el Círculo atrapado en una jugada de poder y la Corte de Vampiros tratando de arrastrarme hacia su mundo, lo único que todos tenemos claro es dejar Katmere significaría mi muerte segura. Tengo que luchar, no solo por mi vida, sino por la de todos. Solo sé que salvar a las personas que amo requerirá sacrificio. Quizás más de lo que puedo dar.",
        category:"Fantasia",
        price: 1850,
        image: 'Furia.jpeg',
        stock: 7,
    },
    {
        id:8,
        title: "Ansia de Tracy Wolff",
        description: "Siento que estoy a punto de llegar al límite. Si intentar graduarme en una escuela para seres sobrenaturales ya era suficientemente estresante, ahora resulta que el estado de mi relación ha pasado de ser complicado a ser un imposible… Y por si no fuera suficiente Bloodletter ha decidido lanzarnos una bomba de proporciones épicas a todos...Pero bueno, si lo piensas, ¿cuándo algo en Katmere Academy ha sido normal?No dejan de suceder cosas: Jaxon se ha vuelto más frío que un invierno de Alaska. El Círculo no está preparado para mi próxima coronación y, como si las cosas no pudieran empeorar, ahora hay una orden de arresto por los supuestos delitos que cometimos Hudson y yo, lo que implica una sentencia de prisión de por vida con una maldición mortal e inquebrantable.",
        category:"Fantasia",
        price: 3100,
        image: 'Ansia.jpeg',
        stock: 56,
    },
    {
        id:9,
        title: "Fulgor de Tracy Wolff",
        description: "Nadie sobrevivió ileso a la última batalla. Flint está enfadado con el mundo, Jaxon se está convirtiendo en algo que no reconozco, y Hudson ha levantado un muro que no estoy segura de poder romper.Ahora se acerca una guerra y no estamos listos. Necesitaríamos un ejército para tener alguna esperanza de ganar. Pero antes de eso necesito encontrar respuestas a las incógnitas sobre mis antepasados. Respuestas que podrían revelar quién es el verdadero monstruo entre nosotros…  en un mundo lleno de vampiros sedientos de sangre, gárgolas inmortales y una antigua batalla entre dos dioses.No hay garantía de que nadie se quede en pie cuando el polvo se asiente, pero si queremos salvar este mundo, no tengo otra opción. Tendré que abrazar cada parte de mí ... incluso las partes que más temo.",
        category:"Fantasia",
        price: 2090,
        image: 'Fulgor.jpeg',
        stock: 34,
    },
    {
        id:10,
        title: "Lore de Alexandra Bracken",
        description: "Cada siete años comienza el agón. Como castigo por la rebelión, nueve dioses griegos son forzados a caminar por la Tierra, entre los mortales, mientras son perseguidos por cazadores, descendientes de antiguos linajes, con ansias de matar a un dios y hacerse con su poder divino y su inmortalidad. Hace mucho tiempo, Lore Perseus huyó de esa competición brutal a raíz del sádico asesinato de su familia por parte de un linaje rival, y dejó atrás las promesas de la caza de la gloria eterna. Durante años ha intentado evadir cualquier pensamiento de venganza hacia el hombre —ahora un dios— responsable de la muerte de su familia. Sin embargo, durante el último agón en Nueva York, dos participantes le piden ayuda: Cástor, su amigo de la infancia, a quien creía muerto, y Atenea, una de las últimas diosas originales, gravemente herida. La diosa le ofrece una alianza contra su enemigo común y, además, una forma de que Lore pueda dejar el agón en el pasado para siempre. Pero la decisión de Lore de vincular su destino al de Atenea y volver a unirse a la caza tendrá un coste mortal, y puede que no sea suficiente para detener la aparición de un nuevo dios con el poder de poner a la humanidad de rodillas.",
        category:"Fantasia",
        price: 2100,
        image: 'Lore.jpeg',
        stock: 89,
    },
    {
        id:11,
        title: "Meal Prep de Paulina Cocina",
        description: "Meal Prep es un manualazo completo para cocinar y guardar, para organizarse en la cocina diaria. Tiene desde cómo guardar cada vegetal hasta sesiones de pollo, legumbres, veganas, sin tacc. De todo. Además de MILES de tips (calditos, cubitos de pesto, pasta de ajo, etc.)",
        category:"Cocina",
        price: 1290,
        image: 'MealPrep.jpeg',
        stock: 12,
    },
    {
        id:12,
        title: "Al Pan, Pan de Paul Fontaine",
        description: "Al pan, pan es un libro con una historia y lleno de recetas. La historia es la de Paul Fontaine, de su periplo vital y profesional que lo llevó a reconvertir su vida, del trabajo en multinacionales a la gastronomía personal. Las recetas son las de siempre, las que todos queremos saber para hacer panes, pizzas, crackers, que abrevan de tradiciones panaderas de todas partes del mundo. Con este libro uno puede seguir usando levadura o iniciarse en los secretos de la masa madre. Hay para todos los gustos.",
        category:"Cocina",
        price: 935,
        image: 'Alpan,pan.jpeg',
        stock: 45,
    },
    {
        id:13,
        title: "100% Dulce de Estefi Colombo",
        description: "Si siempre soñaste con hacer en casa las galletitas de la infancia o tenés ganas de compartir con tu familia las golosinas que disfrutabas en los recreos de la escuela, 100% dulce es el libro para vos. Con la calidez y sensibilidad natural de Estefi Colombo, vas a aprender a preparar las mejores tortas del universo, budines, cuadrados y todo lo que necesitás para tener una vida 100% dulce.",
        category:"Cocina",
        price: 3000,
        image: '100.jpeg',
        stock: 31,
    },
    {
        id:14,
        title: "Sabor, el gordo cocina de Victor Manuel Garcia",
        description: "¿Cómo transformar los ingredientes cotidianos en bombas de Sabor? Con más de ochenta recetas, Víctor Manuel García –El Gordo Cocina– propone estrategias deliciosas para que cada una de tus comidas sea una explosión de placer. Desayunos, sándwiches, picadas y dulces para comer rico.",
        category:"Cocina",
        price: 850,
        image: 'elgordococina.jpeg',
        stock: 56,
    },
    {
        id:15,
        title: "Dulce de leche de Luciano Garcia",
        description: "Cuando era chico, en mi Entre Ríos natal, mi abuela preparaba pan de campo en latas de dulce de batata, eran panes con mucha miga, los cortaba en rebanadas y los untaba con manteca y dulce de leche casero. Eran tiempos en donde no había cultura de comprar tortas. Las tortas se hacían en las casas”, escribe Luciano García en la introducción de su primer libro. Un trabajo recorrido de punta a punta por esta pasión argentina única en el mundo: el dulce de leche.Sin embargo, no es cualquier dulce de leche el que se da cita en estas páginas, sino ese que se deja ver en preparaciones y recetas que van y vuelven de lo exquisito a lo cotidiano, de lo muy elaborado a lo simple, sin perder nunca de vista que el verdadero secreto es mantener vivo un sabor que nos conecta con recuerdos, con nuestra tierra, con el barrio, con la familia.Horneados, postres individuales, recetas para chicos, tortas, bollería, consejos útiles y prácticos hacen de Dulce de leche un libro indispensable no solo para los amantes de la pastelería, sino también para todos aquellos que quieran asomarse por primera vez a su mundo de la mano de Luciano García: pastelero, pero también alquimista, mago y por sobre todas las cosas, alguien cálido, preciso y generoso a la hora de transmitir su enorme saber y experiencia.",
        category:"Cocina",
        price: 1300,
        image: 'Dulcedeleche.jpeg',
        stock: 67,
    },
]

export default products;